elphbolt – elphbolt
elphbolt Program
Nakib Haider Protik
1.0.0
121 statements
Source File
Uses
params
misc
numerics_module
crystal_module
symmetry_module
electron_module
phonon_module
wannier_module
bte_module
bz_sums
interactions
elphbolt is a program for solving the coupled electron-phonon Boltzmann transport equations (e-ph BTEs) as formulated in https://arxiv.org/abs/2109.08547 (2021) with both the electron-phonon and phonon-phonon interactions computed ab initio.
Calls
Contents
Variables
num crys sym wann el ph bt t_all t_event
Variables
Type Attributes Name Initial
type(numerics) :: num
type(crystal) :: crys
type(symmetry) :: sym
type(epw_wannier) :: wann
type(electron) :: el
type(phonon) :: ph
type(bte) :: bt
type(timer) :: t_all
type(timer) :: t_event
Call graph
elphbolt calls calculate_dos, calculate_greq, calculate_3ph_interaction, welcome, calculate_bound_scatt_rates, calculate_eph_interaction_ibzq, calculate_eph_interaction_ibzk, print_message, calculate_gkrp, subtitle, calculate_echimp_interaction_ibzk, calculate_qtf
calculate_greq calls print_message, distribute_points
calculate_3ph_interaction calls print_message, demux_state, distribute_points, delta_fn_tetra, mux_vector, bose, delta_fn_triang, mux_state, exit_with_message, expi
calculate_bound_scatt_rates calls write2file_rank2_real, twonorm
calculate_eph_interaction_ibzq calls print_message, demux_state, distribute_points, delta_fn_tetra, mux_vector, binsearch, bose, delta_fn_triang, mux_state, fermi, exit_with_message
calculate_eph_interaction_ibzk calls print_message, demux_state, distribute_points, delta_fn_tetra, mux_vector, bose, delta_fn_triang, mux_state, fermi, exit_with_message
calculate_gkrp calls print_message, distribute_points
calculate_echimp_interaction_ibzk calls print_message, demux_state, distribute_points, delta_fn_tetra, delta_fn_triang, mux_state
calculate_qtf calls print_message, fermi
mux_vector calls exit_with_message