calculate_echimp_interaction_ibzk – elphbolt
calculate_echimp_interaction_ibzk Subroutine
66 statements
Source File
public subroutine calculate_echimp_interaction_ibzk(crys, el, num)
Parallel driver of |g_e-chimp(k,k')|^2 over IBZ electron states.
Arguments
Type Intent Optional Attributes Name
type(crystal), intent(in) :: crys
type(electron), intent(in) :: el
type(numerics), intent(in) :: num
Calls
Called by
Contents
None
Call graph
calculate_echimp_interaction_ibzk calls delta_fn_tetra, mux_state, distribute_points, print_message, delta_fn_triang, demux_state
elphbolt calls calculate_echimp_interaction_ibzk