calculate_eph_interaction_ibzk – elphbolt
calculate_eph_interaction_ibzk Subroutine
180 statements
Source File
public subroutine calculate_eph_interaction_ibzk(wann, crys, el, ph, num, key)
Parallel driver of g2(k,q) over IBZ electron states.
This subroutine will calculate the full Bloch rep. matrix elements for all the energy window restricted electron-phonon processes for a given irreducible initial electron state = (band, wave vector). This list will be written to disk in files tagged with the muxed state index.
key = 'g', 'X' for vertex, transition probability calculation, respectively.
Arguments
Type Intent Optional Attributes Name
type(epw_wannier), intent(in) :: wann
type(crystal), intent(in) :: crys
type(electron), intent(in) :: el
type(phonon), intent(in) :: ph
type(numerics), intent(in) :: num
character(len=1), intent(in) :: key
Calls
Called by
Contents
None
Call graph
calculate_eph_interaction_ibzk calls demux_state, distribute_points, delta_fn_tetra, mux_vector, bose, print_message, delta_fn_triang, mux_state, fermi, exit_with_message
mux_vector calls exit_with_message
elphbolt calls calculate_eph_interaction_ibzk