calculate_eph_interaction_ibzq – elphbolt
calculate_eph_interaction_ibzq Subroutine
144 statements
Source File
public subroutine calculate_eph_interaction_ibzq(wann, crys, el, ph, num, key)
Parallel driver of g2(q,k) over IBZ phonon states.
This subroutine will calculate the full Bloch rep. matrix elements for all the energy window restricted electron-phonon processes for a given irreducible initial phonon state = (branch, wave vector). This list will be written to disk in files tagged with the muxed state index.
key = 'g', 'Y' for vertex, transition probability calculation, respectively.
Arguments
Type Intent Optional Attributes Name
type(epw_wannier), intent(in) :: wann
type(crystal), intent(in) :: crys
type(electron), intent(in) :: el
type(phonon), intent(in) :: ph
type(numerics), intent(in) :: num
character(len=1), intent(in) :: key
Calls
Called by
Contents
None
Call graph
calculate_eph_interaction_ibzq calls distribute_points, binsearch, exit_with_message, print_message, delta_fn_triang, delta_fn_tetra, demux_state, mux_state, bose, fermi, mux_vector
mux_vector calls exit_with_message
elphbolt calls calculate_eph_interaction_ibzq