calculate_3ph_interaction – elphbolt
calculate_3ph_interaction Subroutine
169 statements
Source File
public subroutine calculate_3ph_interaction(ph, crys, num, key)
Parallel driver of the 3-ph vertex calculator for all IBZ phonon wave vectors. This subroutine calculates |V-(s1|s2q2,s3q3)|^2, W-(s1|s2q2,s3q3), and W+(s1|s2q2,s3q3) for each irreducible phonon and saves the results to disk.
key = 'V', 'W' for vertex, transition probabilitiy calculation, respectively.
Arguments
Type Intent Optional Attributes Name
type(phonon), intent(in) :: ph
type(crystal), intent(in) :: crys
type(numerics), intent(in) :: num
character(len=1), intent(in) :: key
Calls
Called by
Contents
None
Call graph
calculate_3ph_interaction calls expi, delta_fn_tetra, mux_state, distribute_points, mux_vector, bose, print_message, delta_fn_triang, demux_state, exit_with_message
mux_vector calls exit_with_message
elphbolt calls calculate_3ph_interaction