delta_fn_triang – elphbolt
delta_fn_triang Function
55 statements
Source File
public pure function delta_fn_triang(e, ik, ib, mesh, triangmap, triangcount, triang_evals)
Calculate delta function using the triangle method a la Kurganskii et al. Phys. Stat. Sol.(b) 129, 293 (1985)
e Sample energy ik Wave vector index ib Band index mesh Wave vector grid triangmap Wave vector to (triangle, vertex) mapping triangcount Number of triangles in which a wave vector belongs triang_evals Triangles populated with the eigenvalues
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: e
integer(kind=k8), intent(in) :: ik
integer(kind=k8), intent(in) :: ib
integer(kind=k8), intent(in) :: mesh(3)
integer(kind=k8), intent(in) :: triangmap(:,:,:)
integer(kind=k8), intent(in) :: triangcount(:)
real(kind=dp), intent(in) :: triang_evals(:,:,:)
Return Value real(kind=dp)
Called by
Contents
None
Call graph
calculate_eph_interaction_ibzk calls delta_fn_triang
calculate_spectral_transport_coeff calls delta_fn_triang
calculate_echimp_interaction_ibzk calls delta_fn_triang
calculate_3ph_interaction calls delta_fn_triang
calculate_eph_interaction_ibzq calls delta_fn_triang
elphbolt calls calculate_eph_interaction_ibzk, calculate_echimp_interaction_ibzk, calculate_3ph_interaction, calculate_eph_interaction_ibzq