delta_fn_tetra – elphbolt
delta_fn_tetra Function
112 statements
Source File
public pure function delta_fn_tetra(e, ik, ib, mesh, tetramap, tetracount, tetra_evals)
Calculate delta function using the tetraheron method.
e Sample energy ik Wave vector index ib Band index mesh Wave vector grid tetramap Wave vector to (tetrahedron, vertex) mapping tetracount Number of tetrahedra in which a wave vector belongs tetra_evals Tetrahedra populated with the eigenvalues
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: e
integer(kind=k8), intent(in) :: ik
integer(kind=k8), intent(in) :: ib
integer(kind=k8), intent(in) :: mesh(3)
integer(kind=k8), intent(in) :: tetramap(:,:,:)
integer(kind=k8), intent(in) :: tetracount(:)
real(kind=dp), intent(in) :: tetra_evals(:,:,:)
Return Value real(kind=dp)
Called by
Contents
None
Call graph
calculate_3ph_interaction calls delta_fn_tetra
calculate_eph_interaction_ibzk calls delta_fn_tetra
calculate_eph_interaction_ibzq calls delta_fn_tetra
calculate_echimp_interaction_ibzk calls delta_fn_tetra
calculate_spectral_transport_coeff calls delta_fn_tetra
elphbolt calls calculate_3ph_interaction, calculate_eph_interaction_ibzk, calculate_eph_interaction_ibzq, calculate_echimp_interaction_ibzk