demux_vector – elphbolt
demux_vector Subroutine
15 statements
Source File
public subroutine demux_vector(i, v, mesh, base)
Demultiplex index of a single wave vector. i is the multiplexed index of a wave vector (always 1-based). v is the demultiplexed triplet of a wave vector. mesh is the number of wave vectors along the three reciprocal lattice vectors. base chooses whether v has 0- or 1-based indexing.
Arguments
Type Intent Optional Attributes Name
integer(kind=k8), intent(in) :: i
integer(kind=k8), intent(out) :: v(3)
integer(kind=k8), intent(in) :: mesh(3)
integer(kind=k8), intent(in) :: base
Calls
Called by
Contents
None
Call graph
demux_vector calls exit_with_message
form_tetrahedra_3d calls demux_vector
form_triangles calls demux_vector
calculate_wavevectors_full calls demux_vector
find_irred_wedge calls demux_vector