distribute_points – elphbolt
distribute_points Subroutine
13 statements
Source File
public subroutine distribute_points(npts, chunk, istart, iend, num_active_images)
Distribute points among processes
Arguments
Type Intent Optional Attributes Name
integer(kind=k8), intent(in) :: npts
integer(kind=k8), intent(out) :: chunk
integer(kind=k8), intent(out) :: istart
integer(kind=k8), intent(out) :: iend
integer(kind=k8), intent(out) :: num_active_images
Called by
Contents
None
Call graph
calculate_echimp_interaction_ibzk calls distribute_points
find_equiv_map calls distribute_points
calculate_3ph_interaction calls distribute_points
calculate_greq calls distribute_points
find_irred_wedge calls distribute_points, find_equiv_map
calculate_eph_interaction_ibzk calls distribute_points
calculate_gkrp calls distribute_points
calculate_ph_rta_rates calls distribute_points
calculate_eph_interaction_ibzq calls distribute_points
calculate_el_rta_rates calls distribute_points
elphbolt calls calculate_echimp_interaction_ibzk, calculate_3ph_interaction, calculate_greq, calculate_eph_interaction_ibzk, calculate_gkrp, calculate_eph_interaction_ibzq