exit_with_message – elphbolt
exit_with_message Subroutine
7 statements
Source File
public subroutine exit_with_message(message)
Exit with error message.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
Called by
Contents
None
Call graph
calculate_3ph_interaction calls exit_with_message, mux_vector
demux_vector calls exit_with_message
calculate_spectral_transport_coeff calls exit_with_message
mux_vector calls exit_with_message
calculate_eph_interaction_ibzk calls exit_with_message, mux_vector
end_timer calls exit_with_message
calculate_transport_coeff calls exit_with_message
calculate_eph_interaction_ibzq calls exit_with_message, mux_vector
calculate_wavevectors_full calls demux_vector
find_equiv_map calls mux_vector
find_irred_wedge calls demux_vector, find_equiv_map
form_tetrahedra_3d calls demux_vector, mux_vector
elphbolt calls calculate_3ph_interaction, calculate_eph_interaction_ibzk, calculate_eph_interaction_ibzq
form_triangles calls demux_vector, mux_vector