Fermi – elphbolt
Fermi Function
4 statements
Source File
public pure function Fermi(e, chempot, T)
e Energy in eV chempot Chemical potential in eV T temperature in K
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: e
real(kind=dp), intent(in) :: chempot
real(kind=dp), intent(in) :: T
Return Value real(kind=dp)
Called by
Contents
None
Call graph
calculate_transport_coeff calls fermi
calculate_spectral_transport_coeff calls fermi
calculate_eph_interaction_ibzk calls fermi
calculate_eph_interaction_ibzq calls fermi
calculate_qtf calls fermi
elphbolt calls calculate_eph_interaction_ibzk, calculate_eph_interaction_ibzq, calculate_qtf