find_equiv_map – elphbolt
find_equiv_map Subroutine
45 statements
Source File
public subroutine find_equiv_map(nsymm_rot, equiv_map, mesh, qrotations, indexlist)
Subroutine to create the map of equivalent wave vectors.
Arguments
Type Intent Optional Attributes Name
integer(kind=k8), intent(in) :: nsymm_rot
integer(kind=k8), intent(out) :: equiv_map(:,:)
integer(kind=k8), intent(in) :: mesh(3)
real(kind=dp), intent(in) :: qrotations(:,:,:)
integer(kind=k8), intent(in), optional :: indexlist(:)
Calls
Called by
Contents
None
Call graph
find_equiv_map calls mux_vector, demux_mesh, distribute_points
mux_vector calls exit_with_message
find_irred_wedge calls find_equiv_map