find_irred_wedge – elphbolt
find_irred_wedge Subroutine
79 statements
Source File
public subroutine find_irred_wedge(mesh, nwavevecs_irred, wavevecs_irred, indexlist_irred, nequivalent, nsymm_rot, qrotations, ibz2fbz_map, equivalence_map, blocks, indexlist)
Find the irreducible wedge of the FBZ and other quantities. Wedge finding algorithm is inspired by ShengBTE.
mesh is the array of number of points along the reciprocal lattice vectors nwavevecs_irred is the number of irreducible vectors wavevecs_irred are the irreducible vectors indexlist_irred is the list containing the muxed indices of the irreducible wave vectors nequivalent lists the number of equivalent points of each irreducible point ibz2fbz_map contains the map from an irreducible BZ (IBZ) vector to its FBZ images The third axis contains the pair (symmetry index, image) equivalence_map is a map of the equivalent points under rotations blocks chooses whether the FBZ is energy restricted or not indexlist is the sorted list of indices of the wavevectors in the energy restricted FBZ which must be present if blocks is true
Arguments
Type Intent Optional Attributes Name
integer(kind=k8), intent(in) :: mesh(3)
integer(kind=k8), intent(out) :: nwavevecs_irred
real(kind=dp), intent(out), allocatable :: wavevecs_irred(:,:)
integer(kind=k8), intent(out), allocatable :: indexlist_irred(:)
integer(kind=k8), intent(out), allocatable :: nequivalent(:)
integer(kind=k8), intent(in) :: nsymm_rot
real(kind=dp), intent(in) :: qrotations(:,:,:)
integer(kind=k8), intent(out), allocatable :: ibz2fbz_map(:,:,:)
integer(kind=k8), intent(out), allocatable :: equivalence_map(:,:)
logical, intent(in) :: blocks
integer(kind=k8), intent(in), optional :: indexlist(:)
Calls
Contents
None
Call graph
find_irred_wedge calls demux_vector, find_equiv_map, distribute_points
demux_vector calls exit_with_message
find_equiv_map calls distribute_points, demux_mesh, mux_vector
mux_vector calls exit_with_message