form_tetrahedra_3d – elphbolt
form_tetrahedra_3d Subroutine
65 statements
Source File
public subroutine form_tetrahedra_3d(nk, mesh, tetra, tetracount, tetramap, blocks, indexlist)
Form all the tetrahedra of a 3d FBZ mesh.
nk Number of points in the list of FBZ wave vectors mesh Wave vector grid tetra List of the tetrahedra vertices tetracount Number of tetrahedra in which a wave vector belongs tetramap Wave vector to (tetrahedron, vertex) mapping blocks Is the FBZ wave vector list full or energy restricted? indexlist List of muxed indices of the FBZ wave vectors
Arguments
Type Intent Optional Attributes Name
integer(kind=k8), intent(in) :: nk
integer(kind=k8), intent(in) :: mesh(3)
integer(kind=k8), intent(out), allocatable :: tetra(:,:)
integer(kind=k8), intent(out), allocatable :: tetracount(:)
integer(kind=k8), intent(out), allocatable :: tetramap(:,:,:)
logical, intent(in) :: blocks
integer(kind=k8), intent(in), optional :: indexlist(:)
Calls
Contents
None
Call graph
form_tetrahedra_3d calls binsearch, mux_vector, demux_vector
mux_vector calls exit_with_message
demux_vector calls exit_with_message