mux_vector – elphbolt
mux_vector Function
12 statements
Source File
public function mux_vector(v, mesh, base)
Multiplex index of a single wave vector. v is the demultiplexed triplet of a wave vector. i is the multiplexed index of a wave vector (always 1-based). mesh is the number of wave vectors along the three reciprocal lattice vectors. base states whether v has 0- or 1-based indexing.
Arguments
Type Intent Optional Attributes Name
integer(kind=k8), intent(in) :: v(3)
integer(kind=k8), intent(in) :: mesh(3)
integer(kind=k8), intent(in) :: base
Return Value integer(kind=k8)
Calls
Called by
Contents
None
Call graph
mux_vector calls exit_with_message
form_tetrahedra_3d calls mux_vector
calculate_3ph_interaction calls mux_vector
calculate_eph_interaction_ibzq calls mux_vector
form_triangles calls mux_vector
find_equiv_map calls mux_vector
calculate_eph_interaction_ibzk calls mux_vector
find_irred_wedge calls find_equiv_map
elphbolt calls calculate_3ph_interaction, calculate_eph_interaction_ibzq, calculate_eph_interaction_ibzk